// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmSX_pNeu9Me1Gpz-RqfNlAySp0qPk15A',
    appId: '1:1093212454483:web:5739232dacf6c93e3410a6',
    messagingSenderId: '1093212454483',
    projectId: 'movie-app-a72b7',
    authDomain: 'movie-app-a72b7.firebaseapp.com',
    storageBucket: 'movie-app-a72b7.firebasestorage.app',
    measurementId: 'G-8G1PQRZJPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7FpPqv0daK4Navxjw9ub-C9PUr9aPvU',
    appId: '1:1093212454483:android:33f2472d207b2dd93410a6',
    messagingSenderId: '1093212454483',
    projectId: 'movie-app-a72b7',
    storageBucket: 'movie-app-a72b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQznYNMDJIE5Hf8Xo4zDaSQFQNtshScM',
    appId: '1:1093212454483:ios:f7b754ed927126b83410a6',
    messagingSenderId: '1093212454483',
    projectId: 'movie-app-a72b7',
    storageBucket: 'movie-app-a72b7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQznYNMDJIE5Hf8Xo4zDaSQFQNtshScM',
    appId: '1:1093212454483:ios:f7b754ed927126b83410a6',
    messagingSenderId: '1093212454483',
    projectId: 'movie-app-a72b7',
    storageBucket: 'movie-app-a72b7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmSX_pNeu9Me1Gpz-RqfNlAySp0qPk15A',
    appId: '1:1093212454483:web:d57cdad41ce6ab0a3410a6',
    messagingSenderId: '1093212454483',
    projectId: 'movie-app-a72b7',
    authDomain: 'movie-app-a72b7.firebaseapp.com',
    storageBucket: 'movie-app-a72b7.firebasestorage.app',
    measurementId: 'G-F2MQT4Z73X',
  );
}
